version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - REPO=$(aws ecr describe-repositories --repository-names example --output text --query "repositories[0].repositoryUri")
    - IMAGE=$REPO:latest
  build:
    commands:
    - docker build -t $IMAGE .
    - docker build -t nginx:latest
    - docker push $IMAGE
    - docker push nginx:latest

  post_build:
    commands:
    - printf '[{"name":"example","imageUri":"https://github.com/customaddone/WikiForLearningEnglish:latest"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
