version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    environment:
      PHP_HOST: app
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'WikiForLearningEnglish'
    ports:
      - 3306
